elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - logstash-conf:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - rabbitmq
    - elasticsearch
kibana:
  build: kibana/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
rabbitmq:
  image: rabbitmq:3.5
  ports: 
    - "5672:5672"
    - "15672:15672"